### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by absenthecon** [luckydonald/pytgbot#7]
sudo python pager_telegram_forwarder.py --freq="148.5875M" --prot="POCSAG512 POCSAG1200" --min="1" --tID">REDACTED<" --rID=">REDACTED<"

Traceback (most recent call last):
  File "pager_telegram_forwarder.py", line 7, in <module>
    from pytgbot import Bot
  File "build/bdist.linux-armv7l/egg/pytgbot/__init__.py", line 3, in <module>
  File "build/bdist.linux-armv7l/egg/pytgbot/bot.py", line 12, in <module>
  File "/usr/local/lib/python2.7/dist-packages/luckydonald_utils-0.57-py2.7.egg/luckydonaldUtils/exceptions.py", line 11
    def assert_type_or_raise(value, expected_type_clazz_or_tuple, *more_clazzes, exception_clazz=TypeError,
                                                                                               ^
SyntaxError: invalid syntax

**Comment by luckydonald** [comment]
Pytgbot is developed for mainly python 3. This is probably an incompatibility with python 2.7.
I'll look into this.

Sorry, that issue somehow skipped my inbox.

**Comment by luckydonald** [comment]
The software used is https://github.com/stefanmoosbrugger/pager_telegram_forwarder. Maybe there is a better place for reporting that?

In any way, I need additional information:
- Operating system version
- Python version
- pytgbot version
- luckydonald-utils verion
